name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - run: sudo cp -rf build/* /var/www/html/
    - run: sudo rm -r *
